<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BLRKEC334480D" ignored="0" name="Command line test 991840dc-5d47-48d3-be74-d52be6ef9ce0" tests="1" failures="1" timestamp="06 Aug 2018 09:44:55 GMT" time="228.724" errors="0">
  <testcase name="checkoutProduct" time="180.326" classname="app.tests.EndToEndTestCases">
    <failure type="java.lang.AssertionError" message="Sign Out is successful; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Sign Out is successful; expected [true] but found [false]
	at app.pages.HomePage.signOut(Unknown Source)
	at app.tests.EndToEndTestCases.checkoutProduct(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- checkoutProduct -->
</testsuite> <!-- Command line test 991840dc-5d47-48d3-be74-d52be6ef9ce0 -->
